version: "3.9"
services:
  users-grpc:
    image: golang:1.20.5-alpine
    ports:
      - "8000:${PORT}"
    volumes:
      - ./internal/user:/go/src/internal/user
    working_dir: /go/src/internal/user
    environment:
      - GRPC_ENDPOINT=users-grpc:${PORT}
      - SERVER_TYPE=grpc
    env_file:
      - .env
    command: go run main.go
    depends_on:
      - db
  users-gateway:
    image: golang:1.20.5-alpine
    ports:
      - "8080:${HTTP_PORT}"
    volumes:
      - ./internal/user:/go/src/internal/user
    working_dir: /go/src/internal/user
    environment:
      - SERVER_TYPE=gateway
      - GRPC_ENDPOINT=users-grpc:${PORT}
    env_file:
      - .env
    command: go run main.go
    depends_on:
      - db
      - users-grpc
  auth-grpc:
    image: golang:1.20.5-alpine
    ports:
      - "8001:${PORT}"
    volumes:
      - ./internal/auth:/go/src/internal/auth
    working_dir: /go/src/internal/auth
    env_file:
      - .env
    command: go run main.go
    depends_on:
      - db
    environment:
      - GRPC_ENDPOINT=auth-grpc:${PORT}
      - SERVER_TYPE=grpc
  auth-gateway:
    image: golang:1.20.5-alpine
    ports:
      - "8081:${HTTP_PORT}"
    volumes:
      - ./internal/auth:/go/src/internal/auth
    working_dir: /go/src/internal/auth
    env_file:
      - .env
    command: go run main.go
    depends_on:
      - db
      - auth-grpc
    environment:
      - GRPC_ENDPOINT=auth-grpc:${PORT}
      - SERVER_TYPE=gateway
  secret-grpc:
    image: golang:1.20.5-alpine
    ports:
      - "8002:${PORT}"
    volumes:
      - ./internal/secret:/go/src/internal/secret
    working_dir: /go/src/internal/secret
    env_file:
      - .env
    command: go run main.go
    depends_on:
      - db
    environment:
      - GRPC_ENDPOINT=secret-grpc:${PORT}
      - SERVER_TYPE=grpc
  secret-gateway:
    image: golang:1.20.5-alpine
    ports:
      - "8082:${HTTP_PORT}"
    volumes:
      - ./internal/secret:/go/src/internal/secret
    working_dir: /go/src/internal/secret
    env_file:
      - .env
    command: go run main.go
    depends_on:
      - db
      - secret-grpc
    environment:
      - GRPC_ENDPOINT=secret-grpc:${PORT}
      - SERVER_TYPE=gateway
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
    env_file:
      - .env
